# create an empty commit every day

name: "Create an empty Issue"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  commit:
    defaults:
      run:
        shell: pwsh
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
          persist-credentials: false
          token: ${{secrets.PAT}} #If default token of automation user is used, no workflows for merge commit are triggered

      - name: Commit
        run: |
         Write-Output "set user config"
         git config --global user.name 'Daniel Siegl'
         git config --global user.email 'Daniel.Siegl@lieberlieber.com'
         Write-Output "setting remote state"
         git remote set-url origin https://x-access-token:${{secrets.PAT}}@github.com/${{ github.repository }}
         Write-Output "create commit"
         git commit --allow-empty -m "A commit a day keeps the doctor away"
         Write-Output "pushing new commit"
         git push --force-with-lease